name: pre-commit

on:
  pull_request:
  push:
    branches: [devel]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
    - run: |
        go get github.com/project-receptor/receptor@devel
        go test ./...
